import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# ==============================================================================
# MOCK LOG GENERATOR (For instant portfolio demonstration)
# ==============================================================================
def generate_sample_log(filename="srp_operation_log.csv"):
    """
    Simulates a CSV log file generated by main.py over 100 strokes.
    Demonstrates: Normal -> Fluid Pound -> Stepwise Mitigation -> Recovery.
    """
    strokes = np.arange(1, 101)
    spm = np.full(100, 10.0)
    severity = np.zeros(100)
    
    # Phase 1: Normal Operation (Stroke 1-20)
    # severity is 0
    
    # Phase 2: Reservoir Inflow Drops, Fluid Pound Begins (Stroke 21-30)
    severity[20:30] = np.random.uniform(30.0, 45.0, 10)
    
    # Phase 3: AI Intervention - Damped Stepwise Control
    # Step 1 Drop (Max 1.5 SPM)
    spm[30:45] = 8.5
    severity[30:45] = np.random.uniform(15.0, 25.0, 15) # Severity decreases slightly
    
    # Phase 4: AI Intervention - Second Step Drop
    spm[45:60] = 7.0
    severity[45:60] = np.random.uniform(5.0, 10.0, 15) # Severity almost gone
    
    # Phase 5: Recovery / Cooldown Achieved
    spm[60:] = 7.0
    severity[60:] = 0.0 # Well is healed, 0% empty volume
    
    # Add some mechanical noise to severity for realism
    severity += np.random.normal(0, 1.5, 100)
    severity = np.clip(severity, 0, 100) # Ensure it stays between 0-100%
    
    df = pd.DataFrame({
        'stroke_number': strokes,
        'current_spm': spm,
        'pound_severity_pct': severity
    })
    
    df.to_csv(filename, index=False)
    print(f"[SYSTEM] Sample log file '{filename}' generated for dashboarding.")

# ==============================================================================
# DASHBOARD VISUALIZATION ENGINE
# ==============================================================================
def render_executive_dashboard(log_file="srp_operation_log.csv"):
    """
    Reads the operation log and generates a dual-axis executive dashboard
    proving the AI's proactive intervention.
    """
    if not os.path.exists(log_file):
        print(f"[ERROR] Log file {log_file} not found. Generating sample data...")
        generate_sample_log(log_file)
        
    # Read Data
    df = pd.read_csv(log_file)
    
    # Initialize Plot with professional styling
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, ax1 = plt.subplots(figsize=(12, 6))
    
    # Title & Labels
    plt.title('SRP Autonomous Control: Dynamic SPM Optimization vs. Fluid Pound Severity', 
              fontsize=14, fontweight='bold', pad=20)
    
    # --------------------------------------------------------------------------
    # AXIS 1: Strokes Per Minute (SPM) - The AI's Action
    # --------------------------------------------------------------------------
    color1 = '#1f77b4' # Industry standard blue
    ax1.set_xlabel('Time (Stroke Number)', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Motor Speed (SPM)', color=color1, fontsize=12, fontweight='bold')
    line1, = ax1.plot(df['stroke_number'], df['current_spm'], 
                      color=color1, linewidth=3, label='Motor Speed (SPM)', drawstyle='steps-post')
    ax1.tick_params(axis='y', labelcolor=color1)
    ax1.set_ylim(0, 12)
    
    # --------------------------------------------------------------------------
    # AXIS 2: Fluid Pound Severity - The Well's Condition
    # --------------------------------------------------------------------------
    ax2 = ax1.twinx()  # Instantiate a second axes that shares the same x-axis
    color2 = '#d62728' # Danger red
    ax2.set_ylabel('Empty Pump Volume / Severity (%)', color=color2, fontsize=12, fontweight='bold')
    
    # We use a slight alpha (transparency) and fill_between to make the danger zone visually striking
    line2, = ax2.plot(df['stroke_number'], df['pound_severity_pct'], 
                      color=color2, linewidth=2, alpha=0.8, label='Fluid Pound Severity (%)')
    ax2.fill_between(df['stroke_number'], df['pound_severity_pct'], 0, color=color2, alpha=0.1)
    ax2.tick_params(axis='y', labelcolor=color2)
    ax2.set_ylim(0, 100)
    
    # --------------------------------------------------------------------------
    # ANNOTATIONS (Telling the story to Management)
    # --------------------------------------------------------------------------
    # Highlight the intervention points
    intervention_points = df[df['current_spm'].diff() < 0]['stroke_number'].tolist()
    
    for pt in intervention_points:
        ax1.axvline(x=pt, color='grey', linestyle='--', alpha=0.7)
        ax1.annotate('AI Intervention\n(Damped Step Down)', 
                     xy=(pt, df[df['stroke_number'] == pt]['current_spm'].values[0]),
                     xytext=(pt + 2, 10.5),
                     arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=6),
                     fontsize=10, bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.9))

    # Highlight Recovery
    recovery_start = df[(df['pound_severity_pct'] < 5.0) & (df['stroke_number'] > intervention_points[-1])]['stroke_number'].min()
    if pd.notna(recovery_start):
        ax2.annotate('Well Recovered\n(Steady State)', 
                     xy=(recovery_start, 0),
                     xytext=(recovery_start - 10, 20),
                     arrowprops=dict(facecolor='green', shrink=0.05, width=1.5, headwidth=6),
                     fontsize=10, bbox=dict(boxstyle="round,pad=0.3", fc="lightgreen", ec="green", alpha=0.9))

    # Combine Legends from both axes
    lines = [line1, line2]
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper right', frameon=True, shadow=True)
    
    # Render
    fig.tight_layout()
    
    # Save the figure as a high-res image for the GitHub README
    output_img = "dashboard_output.png"
    plt.savefig(output_img, dpi=300)
    print(f"[SYSTEM] Executive Dashboard rendered and saved as '{output_img}'.")
    
    # Display in output (for Colab)
    plt.show()

if __name__ == "__main__":
    # 1. Generate the fake log simulating our system's behavior
    generate_sample_log()
    # 2. Render the beautiful plot
    render_executive_dashboard()
